#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Chromium desktop='^8' state=floating follow=on
bspc rule -a angrysearch state=floating manage=on center=true rectangle=1500x1000+0+0
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart applications
# sxhkd &
picom --config ~/.config/picom/picom.conf --experimental-backend -b &
# dunst & # notfication daemon
# polybar -q &
