#!/bin/bash
set -euo pipefail

# fzf fuzzy search of git repositories
function frepo() {
    (cat $fzf_git_cache 2>/dev/null; gum spin --title "Searching for GitHub Repos..." -- $HOME/scripts/listrepo_gql $GITHUB_SEARCH_OAUTH_TOKEN $GITHUB_ORG) | \
    tee $fzf_git_cache | \
    nauniq | \
    gum filter --limit 1 --placeholder 'Clone a repo' --height 50 --prompt='⬇️ '
}

frepo
