#!/bin/bash
# setup_new_computer_configuration - Setup what can't be setup via dotfiles alone
#
# Generate device unique SSH key for GitHub/GitLab and add to ssh-agent
echo "### Setting up SSH key for GitHub..."
ssh-keygen -t ed25519 -C "$GITHUB_EMAIL" -f $HOME/.ssh/github_ed25519
cat $HOME/.ssh/github_ed25519.pub | clip.exe
touch $HOME/.ssh/allowed_signers
cat $HOME/.ssh/github_ed25519.pub >> ~/.ssh/allowed_signers
eval "$(ssh-agent -s)"
ssh-add $HOME/.ssh/github_ed25519
ssh-add -l
echo "Add the SSH key to your GitHub or GitLab account:
    - On GitHub, navigate to Settings → SSH and GPG keys → New SSH key.
    - On GitLab, go to Preferences → SSH Keys → Add an SSH key."
